import type { Scenario } from "@/lib/types";

/** السيناريوهات = الاحتياجات الشائعة التي يعبر عنها المستفيد بلغته */
export const SCENARIOS: Scenario[] = [
  {
    id: "start-business",
    title: "بدء مشروع تجاري",
    summary: "الاحتياج: بدء مشروع تجاري",
    audience: "business",
    intentKeywords: ["مشروع", "ابدا مشروع", "أبدأ مشروع", "افتح محل", "أفتح محل", "متجر", "مؤسسة", "شركة", "تجارة", "سجل تجاري", "بقالة", "مطعم", "كافيه", "مقهى", "محل"],
    questions: [
      { id: "activity", question: "وش نوع النشاط التجاري؟", options: ["مطعم / كافيه", "متجر تجزئة", "خدمات / مكتب", "متجر إلكتروني", "غير ذلك"] },
      { id: "region", question: "في أي مدينة بمنطقة الحدود الشمالية؟", options: ["عرعر", "رفحاء", "طريف", "العويقيلة", "غير ذلك"] },
      { id: "partners", question: "هل عندك شركاء في المشروع؟", options: ["لا، مؤسسة فردية", "نعم، شركة"], optional: true },
    ],
    serviceIds: ["commercial-register", "balady-license", "final-permit", "zatca-register"],
  },
  {
    id: "hire-employees",
    title: "توظيف عمالة في منشأتي",
    summary: "الاحتياج: توظيف موظفين أو استقدام عمالة",
    audience: "business",
    intentKeywords: ["توظيف", "موظف", "عمالة", "استقدام", "تأشيرة عمل", "قوى", "عامل"],
    questions: [
      { id: "has-cr", question: "هل عندك سجل تجاري ساري؟", options: ["نعم", "لا"] },
      { id: "type", question: "توظيف سعوديين أم استقدام من الخارج؟", options: ["سعوديين", "استقدام", "الاثنين"] },
    ],
    serviceIds: ["commercial-register", "gosi-register", "qiwa-establishment"],
  },
  {
    id: "freelance",
    title: "العمل الحر",
    summary: "الاحتياج: ممارسة عمل حر بشكل نظامي",
    audience: "citizen",
    intentKeywords: ["عمل حر", "فريلانس", "مستقل", "اشتغل لحالي", "وثيقة عمل حر"],
    questions: [{ id: "field", question: "وش مجال العمل الحر؟", options: ["تصميم / برمجة", "تصوير", "تدريب", "غير ذلك"], optional: true }],
    serviceIds: ["freelance-license"],
  },
  {
    id: "protect-brand",
    title: "حماية اسم / شعار مشروعي",
    summary: "الاحتياج: تسجيل علامة تجارية",
    audience: "business",
    intentKeywords: ["علامة تجارية", "شعار", "براند", "احمي اسم", "ملكية فكرية"],
    questions: [],
    serviceIds: ["trademark"],
  },
  {
    id: "renew-id",
    title: "تجديد الهوية الوطنية",
    summary: "الاحتياج: تجديد بطاقة الهوية",
    audience: "citizen",
    intentKeywords: ["تجديد هوية", "تجديد الهوية", "هويتي منتهية", "هوية منتهية", "بطاقة الهوية"],
    questions: [],
    serviceIds: ["national-id-renew"],
  },
  {
    id: "first-id",
    title: "إصدار هوية وطنية لأول مرة",
    summary: "الاحتياج: إصدار هوية لابن/ابنة أتم 15 سنة",
    audience: "citizen",
    intentKeywords: ["هوية لاول مرة", "هوية أول مرة", "اطلع هوية", "أطلع هوية", "هوية لولدي", "هوية لبنتي", "استخراج هوية"],
    questions: [{ id: "age", question: "هل أتم صاحب الطلب 15 سنة؟", options: ["نعم", "لا"] }],
    serviceIds: ["national-id-issue"],
  },
  {
    id: "passport",
    title: "إصدار أو تجديد جواز السفر",
    summary: "الاحتياج: جواز سفر",
    audience: "citizen",
    intentKeywords: ["جواز", "جواز سفر", "ابي اسافر", "أبي أسافر", "سفر", "تجديد جواز"],
    questions: [{ id: "type", question: "إصدار جديد أم تجديد؟", options: ["إصدار جديد", "تجديد"] }],
    serviceIds: ["passport-issue"],
  },
  {
    id: "iqama",
    title: "تجديد الإقامة",
    summary: "الاحتياج: تجديد هوية مقيم",
    audience: "resident",
    intentKeywords: ["اقامة", "إقامة", "تجديد اقامة", "تجديد الإقامة", "هوية مقيم"],
    questions: [{ id: "insurance", question: "هل عندك تأمين صحي ساري؟", options: ["نعم", "لا", "ما أدري"] }],
    serviceIds: ["iqama-renew"],
  },
  {
    id: "driving",
    title: "إصدار رخصة قيادة",
    summary: "الاحتياج: رخصة قيادة لأول مرة",
    audience: "all",
    intentKeywords: ["رخصة قيادة", "اسوق", "أسوق", "سواقة", "قيادة", "رخصة"],
    questions: [{ id: "first", question: "أول مرة أم تجديد؟", options: ["أول مرة", "تجديد"] }],
    serviceIds: ["driving-license"],
  },
  {
    id: "vehicle",
    title: "تجديد استمارة أو نقل ملكية مركبة",
    summary: "الاحتياج: إجراءات المركبة",
    audience: "all",
    intentKeywords: ["استمارة", "سيارة", "سيارتي", "مركبة", "نقل ملكية", "فحص دوري", "اشتري سيارة", "أشتري سيارة"],
    questions: [{ id: "type", question: "تجديد استمارة أم نقل ملكية؟", options: ["تجديد استمارة", "نقل ملكية"] }],
    serviceIds: ["vehicle-registration"],
  },
  {
    id: "newborn",
    title: "تسجيل مولود جديد",
    summary: "الاحتياج: إضافة مولود وإصدار شهادة ميلاد",
    audience: "citizen",
    intentKeywords: ["مولود", "ولادة", "بيبي", "طفل", "شهادة ميلاد", "رزقنا", "ولد"],
    questions: [],
    serviceIds: ["birth-registration"],
  },
  {
    id: "family-visit",
    title: "استقدام عائلتي للزيارة",
    summary: "الاحتياج: تأشيرة زيارة عائلية",
    audience: "resident",
    intentKeywords: ["زيارة", "زيارة عائلية", "اجيب اهلي", "أجيب أهلي", "تأشيرة زيارة", "فيزا"],
    questions: [],
    serviceIds: ["family-visit-visa"],
  },
  {
    id: "rent-home",
    title: "استئجار سكن",
    summary: "الاحتياج: توثيق عقد إيجار سكني",
    audience: "all",
    intentKeywords: ["شقة", "سكن", "استاجر", "أستأجر", "بيت", "عقد ايجار", "عقد إيجار"],
    questions: [],
    serviceIds: ["ejar-residential"],
  },
  {
    id: "social-support",
    title: "الحصول على دعم الضمان الاجتماعي",
    summary: "الاحتياج: التقديم على الضمان الاجتماعي المطور",
    audience: "citizen",
    intentKeywords: ["ضمان", "ضمان اجتماعي", "دعم", "معاش", "مساعدة", "محتاج دعم"],
    questions: [],
    serviceIds: ["social-security"],
  },
  {
    id: "health-appointment",
    title: "حجز موعد طبي",
    summary: "الاحتياج: موعد في مركز صحي",
    audience: "all",
    intentKeywords: ["موعد", "مركز صحي", "دكتور", "طبيب", "مريض", "صحتي"],
    questions: [],
    serviceIds: ["sehhaty-appointment"],
  },
];
