import type { Service } from "@/lib/types";

/**
 * خدمات الأعمال — قاعدة معرفة أولية.
 * ملاحظة: المحتوى يُراجع ويُحدّث من المصادر الرسمية (انظر sources في كل خدمة).
 */
export const BUSINESS_SERVICES: Service[] = [
  {
    id: "commercial-register",
    name: "إصدار السجل التجاري",
    entityId: "mc",
    category: "business",
    description: "إصدار سجل تجاري لمؤسسة فردية أو شركة عبر المركز السعودي للأعمال.",
    url: "https://business.sa",
    requirements: [
      {
        id: "cr-national-id",
        label: "الهوية الوطنية / الإقامة سارية",
        kind: "document",
        description: "هوية سارية المفعول لصاحب المنشأة.",
        obtain: {
          title: "تجديد الهوية الوطنية عبر أبشر",
          entityId: "ahwal",
          serviceId: "national-id-renew",
          url: "https://www.absher.sa",
          steps: ["الدخول إلى أبشر أفراد", "خدمات الأحوال المدنية", "تجديد الهوية الوطنية"],
          why: "لا يمكن إصدار سجل تجاري بهوية منتهية الصلاحية.",
        },
      },
      {
        id: "cr-trade-name",
        label: "اسم تجاري محجوز",
        kind: "condition",
        description: "حجز اسم تجاري غير مستخدم عبر منصة المركز السعودي للأعمال.",
        obtain: {
          title: "حجز اسم تجاري",
          entityId: "sbc",
          url: "https://business.sa",
          steps: ["الدخول إلى منصة المركز السعودي للأعمال", "خدمة حجز اسم تجاري", "اقتراح اسم والتحقق من توفره"],
          durationText: "فوري",
          why: "السجل التجاري يصدر باسم تجاري معتمد ومحجوز.",
        },
      },
      {
        id: "cr-activity",
        label: "تحديد النشاط التجاري (ISIC)",
        kind: "condition",
        description: "اختيار النشاط التجاري من دليل الأنشطة الاقتصادية.",
      },
      {
        id: "cr-absher",
        label: "حساب أبشر / النفاذ الوطني فعّال",
        kind: "condition",
      },
      {
        id: "cr-national-address",
        label: "عنوان وطني مسجل",
        kind: "document",
        obtain: {
          title: "التسجيل في العنوان الوطني",
          entityId: "spl",
          serviceId: "national-address",
          url: "https://address.gov.sa",
          steps: ["الدخول إلى منصة العنوان الوطني", "تسجيل عنوان الأفراد / المنشآت", "التحقق وتأكيد العنوان"],
          durationText: "فوري",
          why: "العنوان الوطني مطلوب لربط المنشأة بموقعها الرسمي.",
        },
      },
    ],
    prerequisites: [],
    steps: [
      "الدخول إلى منصة المركز السعودي للأعمال عبر النفاذ الوطني",
      "اختيار خدمة إصدار سجل تجاري (مؤسسة / شركة)",
      "حجز الاسم التجاري وتحديد النشاط",
      "استكمال البيانات وسداد الرسوم",
      "استلام السجل التجاري إلكترونياً",
    ],
    fees: "حسب مدة السجل ونوع المنشأة (تُعرض عند التقديم)",
    duration: "فوري إلى يوم عمل",
    sources: ["https://business.sa", "https://mc.gov.sa"],
    keywords: ["سجل تجاري", "سجل", "مؤسسة", "شركة", "مشروع", "تجارة", "محل", "نشاط تجاري"],
  },
  {
    id: "balady-license",
    name: "إصدار رخصة البلدية (رخصة نشاط تجاري)",
    entityId: "balady",
    category: "business",
    description: "رخصة مزاولة النشاط التجاري للمحل من أمانة منطقة الحدود الشمالية عبر منصة بلدي.",
    url: "https://balady.gov.sa",
    requirements: [
      {
        id: "bl-lease",
        label: "عقد الإيجار",
        kind: "document",
        description: "عقد إيجار إلكتروني موثق للمحل عبر منصة إيجار (أو صك ملكية).",
        obtain: {
          title: "توثيق عقد إيجار تجاري في منصة إيجار",
          entityId: "ejar",
          serviceId: "ejar-commercial",
          url: "https://www.ejar.sa",
          steps: [
            "الاتفاق مع المؤجر على المحل",
            "التوجه إلى وسيط عقاري معتمد أو إنشاء العقد عبر منصة إيجار",
            "توثيق العقد إلكترونياً واعتماده من الطرفين",
            "الحصول على رقم العقد الموثق",
          ],
          durationText: "يوم واحد تقريباً",
          why: "عقد الإيجار مطلوب لإصدار رخصة البلدية ولإثبات موقع النشاط.",
        },
      },
      {
        id: "bl-compliance",
        label: "استيفاء اشتراطات الموقع",
        kind: "condition",
        description: "مطابقة المحل للاشتراطات البلدية للنشاط (المساحة، السلامة، اللوحة).",
      },
      {
        id: "bl-civil-defense",
        label: "شهادة سلامة (الدفاع المدني) إن لزم",
        kind: "document",
        description: "تُطلب لبعض الأنشطة حسب التصنيف.",
        obtain: {
          title: "إصدار شهادة سلامة عبر منصة سلامة",
          url: "https://salamah.998.gov.sa",
          steps: ["التسجيل في منصة سلامة", "طلب ترخيص سلامة للنشاط", "تركيب أدوات السلامة عبر مقاول معتمد", "إصدار الشهادة"],
          why: "الأنشطة ذات الخطورة تتطلب شهادة سلامة قبل الترخيص.",
        },
      },
    ],
    prerequisites: ["commercial-register"],
    steps: [
      "الدخول إلى منصة بلدي عبر النفاذ الوطني",
      "خدمة إصدار رخصة تجارية",
      "اختيار السجل التجاري والنشاط والموقع",
      "إرفاق عقد الإيجار والمستندات",
      "سداد الرسوم واستلام الرخصة",
    ],
    fees: "حسب النشاط والمساحة",
    duration: "فوري بعد استيفاء الاشتراطات",
    sources: ["https://balady.gov.sa"],
    keywords: ["رخصة بلدية", "رخصة", "بلدي", "محل", "أمانة", "رخصة تجارية"],
  },
  {
    id: "ejar-commercial",
    name: "توثيق عقد إيجار تجاري",
    entityId: "ejar",
    category: "housing",
    description: "توثيق عقد إيجار المحل أو المكتب إلكترونياً عبر منصة إيجار.",
    url: "https://www.ejar.sa",
    requirements: [
      { id: "ej-parties", label: "بيانات المؤجر والمستأجر", kind: "condition" },
      { id: "ej-property", label: "بيانات العقار (صك / رقم الوحدة)", kind: "document" },
    ],
    prerequisites: [],
    steps: ["إنشاء العقد عبر منصة إيجار أو وسيط معتمد", "اعتماد الطرفين", "الحصول على رقم العقد"],
    duration: "يوم واحد تقريباً",
    sources: ["https://www.ejar.sa"],
    keywords: ["عقد إيجار", "ايجار", "إيجار", "محل", "مكتب"],
  },
  {
    id: "final-permit",
    name: "استكمال المتطلبات وإصدار التراخيص التخصصية",
    entityId: "sbc",
    category: "business",
    description: "تراخيص الجهات ذات العلاقة حسب النشاط (مثل الغذاء والدواء، السياحة، الصحة).",
    url: "https://business.sa",
    requirements: [
      { id: "fp-activity-license", label: "ترخيص الجهة المختصة بالنشاط (إن وجد)", kind: "document" },
    ],
    prerequisites: ["balady-license"],
    steps: ["التحقق من اشتراطات النشاط في دليل الأنشطة", "التقديم على الترخيص التخصصي", "الربط مع السجل التجاري"],
    sources: ["https://business.sa"],
    keywords: ["ترخيص", "تراخيص", "نشاط"],
  },
  {
    id: "zatca-register",
    name: "التسجيل في الزكاة وضريبة القيمة المضافة",
    entityId: "zatca",
    category: "tax",
    description: "فتح ملف زكوي وضريبي للمنشأة والتسجيل في ضريبة القيمة المضافة عند تجاوز الحد.",
    url: "https://zatca.gov.sa",
    requirements: [
      { id: "zt-cr", label: "السجل التجاري", kind: "document" },
      { id: "zt-bank", label: "حساب بنكي (IBAN) باسم المنشأة", kind: "document" },
    ],
    prerequisites: ["commercial-register"],
    steps: ["الدخول إلى بوابة الهيئة", "التسجيل كمكلف", "إضافة بيانات المنشأة والنشاط", "استلام الرقم الضريبي"],
    sources: ["https://zatca.gov.sa"],
    keywords: ["ضريبة", "زكاة", "القيمة المضافة", "رقم ضريبي"],
  },
  {
    id: "gosi-register",
    name: "تسجيل المنشأة في التأمينات الاجتماعية",
    entityId: "gosi",
    category: "labor",
    description: "فتح اشتراك للمنشأة وتسجيل الموظفين في التأمينات الاجتماعية.",
    url: "https://www.gosi.gov.sa",
    requirements: [{ id: "gs-cr", label: "السجل التجاري", kind: "document" }],
    prerequisites: ["commercial-register"],
    steps: ["الدخول إلى بوابة التأمينات", "تسجيل منشأة جديدة", "إضافة المشتركين"],
    sources: ["https://www.gosi.gov.sa"],
    keywords: ["تأمينات", "موظفين", "اشتراك"],
  },
  {
    id: "qiwa-establishment",
    name: "فتح ملف منشأة في منصة قوى",
    entityId: "qiwa",
    category: "labor",
    description: "إنشاء ملف المنشأة في قوى لإدارة العمالة والتأشيرات والعقود.",
    url: "https://qiwa.sa",
    requirements: [
      { id: "qw-cr", label: "السجل التجاري", kind: "document" },
      { id: "qw-gosi", label: "اشتراك التأمينات الاجتماعية", kind: "document" },
    ],
    prerequisites: ["commercial-register", "gosi-register"],
    steps: ["التسجيل في قوى", "ربط المنشأة", "إدارة الخدمات (تأشيرات، عقود، نطاقات)"],
    sources: ["https://qiwa.sa"],
    keywords: ["قوى", "عمالة", "تأشيرة عمل", "توظيف"],
  },
  {
    id: "freelance-license",
    name: "إصدار وثيقة العمل الحر",
    entityId: "freelance",
    category: "business",
    description: "وثيقة رسمية لممارسة العمل الحر في مهنة معتمدة دون سجل تجاري.",
    url: "https://freelance.sa",
    requirements: [
      { id: "fl-id", label: "هوية وطنية سارية", kind: "document" },
      { id: "fl-absher", label: "حساب أبشر فعّال", kind: "condition" },
    ],
    prerequisites: [],
    steps: ["الدخول إلى منصة العمل الحر عبر النفاذ", "اختيار المهنة", "إصدار الوثيقة"],
    fees: "مجاناً",
    duration: "فوري",
    sources: ["https://freelance.sa"],
    keywords: ["عمل حر", "فريلانس", "وثيقة", "مستقل"],
  },
  {
    id: "trademark",
    name: "تسجيل علامة تجارية",
    entityId: "saip",
    category: "business",
    description: "حماية اسم أو شعار المشروع بتسجيله كعلامة تجارية.",
    url: "https://www.saip.gov.sa",
    requirements: [
      { id: "tm-logo", label: "صورة العلامة / الشعار", kind: "document" },
      { id: "tm-class", label: "تحديد فئة المنتجات أو الخدمات", kind: "condition" },
    ],
    prerequisites: [],
    steps: ["التقديم عبر بوابة الهيئة", "الفحص والنشر", "الاعتراضات", "الإصدار"],
    sources: ["https://www.saip.gov.sa"],
    keywords: ["علامة تجارية", "شعار", "براند", "ملكية فكرية"],
  },
];
