import type { Service } from "@/lib/types";

/**
 * خدمات الأفراد — قاعدة معرفة أولية.
 * ملاحظة: المحتوى يُراجع ويُحدّث من المصادر الرسمية (انظر sources في كل خدمة).
 */
export const INDIVIDUAL_SERVICES: Service[] = [
  {
    id: "national-id-issue",
    name: "إصدار الهوية الوطنية لأول مرة",
    entityId: "ahwal",
    category: "civil",
    description: "إصدار بطاقة الهوية الوطنية لمن أتم 15 عاماً.",
    url: "https://www.absher.sa",
    requirements: [
      { id: "nid-age", label: "إتمام 15 سنة", kind: "condition" },
      { id: "nid-family-record", label: "سجل الأسرة (لولي الأمر)", kind: "document" },
      { id: "nid-photo", label: "صورة شخصية حديثة", kind: "document" },
      { id: "nid-appointment", label: "موعد في الأحوال المدنية", kind: "condition",
        obtain: { title: "حجز موعد في أبشر", entityId: "ahwal", url: "https://www.absher.sa", steps: ["أبشر أفراد", "المواعيد", "الأحوال المدنية"], why: "زيارة الأحوال تتطلب موعداً مسبقاً." } },
    ],
    prerequisites: [],
    steps: ["حجز موعد عبر أبشر", "زيارة مكتب الأحوال المدنية بالمستندات", "استلام البطاقة"],
    sources: ["https://www.absher.sa"],
    keywords: ["هوية", "بطاقة هوية", "هوية وطنية", "احوال", "أحوال"],
  },
  {
    id: "national-id-renew",
    name: "تجديد الهوية الوطنية",
    entityId: "ahwal",
    category: "civil",
    description: "تجديد بطاقة الهوية الوطنية إلكترونياً عبر أبشر.",
    url: "https://www.absher.sa",
    requirements: [
      { id: "nidr-photo", label: "صورة شخصية بالمواصفات", kind: "document" },
      { id: "nidr-absher", label: "حساب أبشر فعّال", kind: "condition" },
    ],
    prerequisites: [],
    steps: ["أبشر أفراد", "خدمات الأحوال المدنية", "تجديد الهوية الوطنية", "رفع الصورة وسداد الرسوم", "الاستلام أو التوصيل"],
    duration: "أيام معدودة",
    sources: ["https://www.absher.sa"],
    keywords: ["تجديد هوية", "تجديد الهوية", "هوية منتهية"],
  },
  {
    id: "passport-issue",
    name: "إصدار / تجديد جواز السفر",
    entityId: "jawazat",
    category: "passports",
    description: "إصدار جواز سفر سعودي أو تجديده إلكترونياً عبر أبشر.",
    url: "https://www.absher.sa",
    requirements: [
      { id: "pp-id", label: "هوية وطنية سارية", kind: "document",
        obtain: { title: "تجديد الهوية الوطنية", entityId: "ahwal", serviceId: "national-id-renew", url: "https://www.absher.sa", steps: ["أبشر أفراد", "تجديد الهوية"], why: "الجواز يصدر بناءً على هوية سارية." } },
      { id: "pp-fees", label: "سداد رسوم الإصدار", kind: "condition" },
      { id: "pp-address", label: "عنوان وطني للتوصيل", kind: "document",
        obtain: { title: "التسجيل في العنوان الوطني", entityId: "spl", serviceId: "national-address", url: "https://address.gov.sa", steps: ["منصة العنوان الوطني", "تسجيل عنوان"], why: "الجواز يُرسل إلى العنوان الوطني." } },
    ],
    prerequisites: [],
    steps: ["أبشر أفراد", "خدمات الجوازات", "إصدار / تجديد جواز", "سداد الرسوم", "الاستلام عبر البريد"],
    duration: "أيام عمل",
    sources: ["https://www.absher.sa"],
    keywords: ["جواز", "جواز سفر", "سفر", "تجديد جواز"],
  },
  {
    id: "iqama-renew",
    name: "تجديد الإقامة",
    entityId: "jawazat",
    category: "passports",
    description: "تجديد هوية مقيم عبر أبشر أعمال / أفراد.",
    url: "https://www.absher.sa",
    requirements: [
      { id: "iq-insurance", label: "تأمين صحي ساري", kind: "document",
        obtain: { title: "شراء وثيقة تأمين صحي", steps: ["التواصل مع شركة تأمين معتمدة", "إصدار الوثيقة وربطها بمجلس الضمان الصحي"], why: "التأمين الصحي شرط نظامي لتجديد الإقامة." } },
      { id: "iq-fees", label: "سداد رسوم الإقامة والمرافقين", kind: "condition" },
      { id: "iq-no-violations", label: "عدم وجود مخالفات مرورية غير مسددة", kind: "condition" },
      { id: "iq-passport", label: "جواز سفر ساري", kind: "document" },
    ],
    prerequisites: [],
    steps: ["سداد الرسوم", "أبشر", "تجديد الإقامة", "التحقق من التحديث"],
    sources: ["https://www.absher.sa"],
    keywords: ["إقامة", "اقامة", "تجديد الإقامة", "مقيم", "هوية مقيم"],
  },
  {
    id: "driving-license",
    name: "إصدار رخصة القيادة",
    entityId: "muroor",
    category: "traffic",
    description: "إصدار رخصة قيادة خاصة لأول مرة عبر مدارس تعليم القيادة وأبشر.",
    url: "https://www.absher.sa",
    requirements: [
      { id: "dl-age", label: "إتمام السن النظامي", kind: "condition" },
      { id: "dl-medical", label: "الفحص الطبي", kind: "document",
        obtain: { title: "إجراء الفحص الطبي", steps: ["زيارة مركز فحص معتمد", "رفع النتيجة إلكترونياً"], why: "الفحص الطبي شرط لإصدار الرخصة." } },
      { id: "dl-school", label: "اجتياز اختبار مدرسة القيادة", kind: "condition",
        obtain: { title: "التسجيل في مدرسة تعليم القيادة", steps: ["حجز موعد في المدرسة", "اجتياز الاختبار النظري والعملي"], why: "اجتياز الاختبار شرط للإصدار." } },
      { id: "dl-fees", label: "سداد الرسوم", kind: "condition" },
    ],
    prerequisites: [],
    steps: ["التسجيل في مدرسة القيادة", "الفحص الطبي", "اجتياز الاختبارات", "إصدار الرخصة عبر أبشر"],
    sources: ["https://www.absher.sa"],
    keywords: ["رخصة قيادة", "قيادة", "رخصة", "مرور", "سواقة"],
  },
  {
    id: "vehicle-registration",
    name: "تجديد رخصة السير / نقل ملكية مركبة",
    entityId: "muroor",
    category: "traffic",
    description: "تجديد استمارة المركبة أو نقل ملكيتها إلكترونياً عبر أبشر.",
    url: "https://www.absher.sa",
    requirements: [
      { id: "vr-inspection", label: "الفحص الدوري ساري", kind: "document",
        obtain: { title: "إجراء الفحص الدوري", steps: ["حجز موعد في مركز الفحص الدوري", "اجتياز الفحص"], why: "الفحص الدوري شرط لتجديد الاستمارة." } },
      { id: "vr-insurance", label: "تأمين ساري على المركبة", kind: "document" },
      { id: "vr-violations", label: "سداد المخالفات المرورية", kind: "condition" },
    ],
    prerequisites: [],
    steps: ["أبشر", "خدمات المركبات", "تجديد الاستمارة / نقل ملكية", "السداد"],
    sources: ["https://www.absher.sa"],
    keywords: ["استمارة", "سيارة", "مركبة", "نقل ملكية", "تجديد استمارة", "فحص دوري"],
  },
  {
    id: "birth-registration",
    name: "تسجيل مولود جديد",
    entityId: "ahwal",
    category: "civil",
    description: "تسجيل المولود في سجل الأسرة وإصدار شهادة الميلاد.",
    url: "https://www.absher.sa",
    requirements: [
      { id: "br-hospital", label: "تبليغ الولادة من المستشفى", kind: "document" },
      { id: "br-family-record", label: "سجل الأسرة", kind: "document" },
      { id: "br-marriage", label: "عقد الزواج", kind: "document" },
    ],
    prerequisites: [],
    steps: ["تبليغ الولادة", "أبشر > الأحوال المدنية > تسجيل مولود", "إصدار شهادة الميلاد"],
    sources: ["https://www.absher.sa"],
    keywords: ["مولود", "ولادة", "شهادة ميلاد", "طفل", "بيبي"],
  },
  {
    id: "family-visit-visa",
    name: "تأشيرة زيارة عائلية",
    entityId: "mofa",
    category: "passports",
    description: "طلب تأشيرة زيارة عائلية للمقيمين عبر منصة التأشيرات.",
    url: "https://visa.mofa.gov.sa",
    requirements: [
      { id: "fv-iqama", label: "إقامة سارية", kind: "document" },
      { id: "fv-relation", label: "إثبات صلة القرابة", kind: "document" },
      { id: "fv-chamber", label: "تصديق من جهة العمل / الغرفة التجارية", kind: "document" },
    ],
    prerequisites: [],
    steps: ["تعبئة الطلب في منصة التأشيرات", "التصديق", "المتابعة عبر المنصة"],
    sources: ["https://visa.mofa.gov.sa"],
    keywords: ["زيارة", "تأشيرة", "زيارة عائلية", "فيزا"],
  },
  {
    id: "ejar-residential",
    name: "توثيق عقد إيجار سكني",
    entityId: "ejar",
    category: "housing",
    description: "توثيق عقد إيجار السكن إلكترونياً عبر منصة إيجار.",
    url: "https://www.ejar.sa",
    requirements: [
      { id: "ejr-parties", label: "بيانات المؤجر والمستأجر", kind: "condition" },
      { id: "ejr-property", label: "بيانات العقار", kind: "document" },
    ],
    prerequisites: [],
    steps: ["وسيط عقاري معتمد أو منصة إيجار", "إنشاء العقد", "اعتماد الطرفين"],
    sources: ["https://www.ejar.sa"],
    keywords: ["سكن", "شقة", "عقد سكني", "إيجار سكني", "ايجار"],
  },
  {
    id: "national-address",
    name: "التسجيل في العنوان الوطني",
    entityId: "spl",
    category: "civil",
    description: "تسجيل العنوان الوطني للأفراد والمنشآت عبر منصة سبل.",
    url: "https://address.gov.sa",
    requirements: [{ id: "na-id", label: "هوية وطنية / إقامة", kind: "document" }],
    prerequisites: [],
    steps: ["الدخول إلى منصة العنوان الوطني", "تسجيل العنوان", "التحقق"],
    fees: "مجاناً",
    duration: "فوري",
    sources: ["https://address.gov.sa"],
    keywords: ["عنوان وطني", "عنوان", "سبل", "بريد"],
  },
  {
    id: "sehhaty-appointment",
    name: "حجز موعد في المركز الصحي",
    entityId: "moh",
    category: "health",
    description: "حجز موعد في مركز الرعاية الصحية الأولية عبر تطبيق صحتي.",
    url: "https://www.moh.gov.sa",
    requirements: [{ id: "sh-account", label: "حساب في تطبيق صحتي", kind: "condition" }],
    prerequisites: [],
    steps: ["تحميل تطبيق صحتي", "المواعيد", "اختيار المركز والوقت"],
    fees: "مجاناً",
    sources: ["https://www.moh.gov.sa"],
    keywords: ["موعد", "مركز صحي", "صحتي", "طبيب", "مستشفى"],
  },
  {
    id: "social-security",
    name: "التسجيل في الضمان الاجتماعي المطور",
    entityId: "hrsd",
    category: "social",
    description: "التقديم على معاش الضمان الاجتماعي المطور للأسر المستحقة.",
    url: "https://sbis.hrsd.gov.sa",
    requirements: [
      { id: "ss-id", label: "هوية وطنية سارية", kind: "document" },
      { id: "ss-iban", label: "حساب بنكي (IBAN)", kind: "document" },
      { id: "ss-address", label: "عنوان وطني", kind: "document",
        obtain: { title: "التسجيل في العنوان الوطني", entityId: "spl", serviceId: "national-address", url: "https://address.gov.sa", steps: ["منصة العنوان الوطني", "تسجيل عنوان"], why: "العنوان الوطني مطلوب للتحقق من الأهلية." } },
      { id: "ss-income", label: "بيانات الدخل والأسرة", kind: "condition" },
    ],
    prerequisites: [],
    steps: ["الدخول إلى منصة الدعم والحماية الاجتماعية", "تعبئة الطلب", "دراسة الأهلية", "صرف المعاش"],
    sources: ["https://sbis.hrsd.gov.sa"],
    keywords: ["ضمان", "ضمان اجتماعي", "معاش", "دعم", "مساعدة مالية"],
  },
];
