import type { Service } from "@/lib/types";

/**
 * خدمات الأفراد — تم التحقق من المحتوى من المصادر الحكومية الرسمية بتاريخ 2026-09-12.
 * التفاصيل الكاملة والروابط: docs/research-individual.md
 */
const VERIFIED = "2026-09-12";

const NATIONAL_ADDRESS_OBTAIN = {
  title: "التسجيل في العنوان الوطني (مجاناً)",
  entityId: "spl",
  serviceId: "national-address",
  url: "https://register.address.gov.sa/ar/individual/",
  steps: ["الدخول إلى صفحة تسجيل الأفراد في العنوان الوطني", "الدخول عبر النفاذ الوطني الموحد", "تعبئة بيانات العنوان والتسجيل", "التفعيل خلال 24 ساعة"],
  durationText: "فوري (التفعيل خلال 24 ساعة)",
  why: "العنوان الوطني شرط لخدمات التوصيل في أبشر (الهوية، الجواز، سجل الأسرة، شهادة الميلاد، رخصة القيادة).",
};

const ABSHER_OBTAIN = {
  title: "تفعيل حساب أبشر أفراد",
  entityId: "ahwal",
  url: "https://www.absher.sa",
  steps: ["التسجيل في أبشر أفراد برقم الهوية والجوال", "تفعيل الحساب عبر أجهزة الخدمة الذاتية أو البنك أو مكاتب الأحوال", "تسجيل الدخول واستخدام الخدمات"],
  durationText: "فوري بعد التفعيل",
  why: "جميع خدمات الأحوال المدنية والجوازات والمرور الإلكترونية تتم عبر أبشر.",
};

export const INDIVIDUAL_SERVICES: Service[] = [
  {
    id: "national-id-issue",
    name: "إصدار هوية وطنية لفرد أسرة (لأول مرة)",
    entityId: "ahwal",
    category: "civil",
    description:
      "إصدار الهوية الوطنية لأول مرة لفرد الأسرة (6 إلى 19 عاماً) إلكترونياً عبر أبشر بواسطة أحد الوالدين، مع تسجيل السمات الحيوية في فرع الأحوال المدنية.",
    url: "https://www.absher.sa",
    requirements: [
      { id: "nid-age", label: "عمر فرد الأسرة بين 6 و19 عاماً", kind: "condition", description: "ولا يكون له هوية أو طلب سابق." },
      { id: "nid-parent-absher", label: "حساب أبشر مفعّل لأحد الوالدين", kind: "condition", description: "يقتصر على الوالد الحاضن في الأسر الحاضنة.", obtain: ABSHER_OBTAIN },
      { id: "nid-address", label: "عنوان وطني مسجل للمستفيد", kind: "document", obtain: NATIONAL_ADDRESS_OBTAIN },
      { id: "nid-photo", label: "صورة شخصية مطابقة للاشتراطات", kind: "document", description: "يُرفض الطلب إن لم تتطابق الصورة." },
      { id: "nid-fines", label: "عدم وجود غرامات غير مسددة لدى الأحوال المدنية", kind: "condition" },
      { id: "nid-delivery", label: "سداد أجور التوصيل", kind: "condition" },
    ],
    prerequisites: [],
    steps: [
      "تسجيل الدخول إلى أبشر أفراد",
      "خدمات الأحوال المدنية → خدمات الهوية الوطنية → إصدار هوية لفرد أسرة",
      "اختيار فرد الأسرة المستوفي للشروط",
      "إرفاق الصورة الشخصية ومراجعة البيانات",
      "اختيار المنطقة والمدينة والحي وإدخال رقم الجوال",
      "الإقرار والدفع وحفظ الرقم المرجعي",
      "تسجيل السمات الحيوية في فرع الأحوال المدنية",
    ],
    fees: "مجاناً (أجور توصيل فقط)",
    duration: "فوري (تقديم الطلب)",
    sources: ["https://my.gov.sa/ar/services/152957"],
    keywords: ["هوية", "بطاقة هوية", "هوية وطنية", "احوال", "أحوال", "هوية لولدي", "هوية لبنتي"],
    lastVerified: VERIFIED,
  },
  {
    id: "national-id-renew",
    name: "تجديد الهوية الوطنية",
    entityId: "ahwal",
    category: "civil",
    description: "تجديد بطاقة الهوية الوطنية إلكترونياً عبر أبشر أو توكلنا عندما يتبقى 180 يوماً أو أقل على انتهائها.",
    url: "https://www.absher.sa/wps/vanityurl/ar/guide/National-ID-Renewal-Service",
    requirements: [
      { id: "nidr-absher", label: "حساب أبشر مفعّل (هوية رقمية)", kind: "condition", obtain: ABSHER_OBTAIN },
      { id: "nidr-window", label: "متبقٍ 180 يوماً أو أقل على انتهاء الهوية", kind: "condition" },
      { id: "nidr-photo", label: "صورة شخصية جديدة مطابقة للاشتراطات", kind: "document", description: "تحقق آلي بتقنية التعرف على الوجه." },
      { id: "nidr-address", label: "عنوان وطني مسجل", kind: "document", obtain: NATIONAL_ADDRESS_OBTAIN },
      { id: "nidr-fines", label: "عدم وجود غرامات غير مسددة لدى الأحوال المدنية", kind: "condition" },
    ],
    prerequisites: [],
    steps: [
      "الدخول إلى أبشر أفراد",
      "خدمات الأحوال المدنية → خدمات الهوية الوطنية → تجديد الهوية الوطنية",
      "إرفاق صورة جديدة والتحقق الآلي منها",
      "تحديد عنوان التوصيل ودفع أجور التوصيل (39.91 ريال)",
      "تأكيد الطلب وحفظ الرقم المرجعي",
    ],
    fees: "مجاناً + أجور توصيل 39.91 ريال",
    duration: "فوري",
    sources: ["https://my.gov.sa/ar/services/143495", "https://www.absher.sa/wps/vanityurl/ar/guide/National-ID-Renewal-Service"],
    keywords: ["تجديد هوية", "تجديد الهوية", "هوية منتهية", "هويتي"],
    lastVerified: VERIFIED,
  },
  {
    id: "passport-issue",
    name: "إصدار / تجديد جواز السفر السعودي",
    entityId: "jawazat",
    category: "passports",
    description: "إصدار جواز سفر سعودي أو تجديده إلكترونياً عبر أبشر. أقل من 21 سنة: 5 سنوات فقط؛ 21 فأكثر: 5 أو 10 سنوات. يُسلَّم عبر الناقل البريدي.",
    url: "https://www.absher.sa",
    requirements: [
      {
        id: "pp-id",
        label: "هوية وطنية سارية",
        kind: "document",
        obtain: { title: "تجديد الهوية الوطنية", entityId: "ahwal", serviceId: "national-id-renew", url: "https://www.absher.sa", steps: ["أبشر أفراد", "خدمات الأحوال المدنية", "تجديد الهوية الوطنية"], durationText: "فوري", why: "الجواز يصدر بناءً على هوية وطنية سارية." },
      },
      { id: "pp-biometrics", label: "بصمة وصورة مسجلة في أنظمة وزارة الداخلية", kind: "condition" },
      { id: "pp-inside", label: "التواجد داخل المملكة عند الطلب", kind: "condition" },
      { id: "pp-no-other", label: "عدم وجود جواز سارٍ آخر", kind: "condition", description: "للتجديد: مضي 6 أشهر على إصدار الجواز الحالي وألا يكون مفقوداً أو تالفاً." },
      { id: "pp-address", label: "عنوان وطني محدث للتوصيل", kind: "document", obtain: NATIONAL_ADDRESS_OBTAIN },
      { id: "pp-violations", label: "سداد المخالفات المرورية", kind: "condition" },
      { id: "pp-fees", label: "سداد رسوم الإصدار (300 ريال لـ 5 سنوات)", kind: "condition" },
    ],
    prerequisites: [],
    steps: [
      "الدخول إلى أبشر أفراد → خدماتي → الجوازات",
      "إصدار / تجديد جواز السفر السعودي",
      "تحديد المدة (5 أو 10 سنوات) والإقرار",
      "اختيار عنوان التوصيل وطريقته",
      "مراجعة الطلب وسداد الرسوم",
      "استلام الجواز عبر الناقل البريدي",
    ],
    fees: "300 ريال لمدة 5 سنوات (رسوم 10 سنوات تُعرض عند التقديم)",
    duration: "فوري (تقديم الطلب) + التوصيل",
    sources: ["https://my.gov.sa/ar/services/112093", "https://my.gov.sa/ar/services/112090"],
    keywords: ["جواز", "جواز سفر", "سفر", "تجديد جواز", "اسافر", "أسافر"],
    lastVerified: VERIFIED,
  },
  {
    id: "iqama-renew",
    name: "تجديد الإقامة (هوية مقيم)",
    entityId: "jawazat",
    category: "passports",
    description: "تجديد هوية مقيم عبر أبشر أفراد (لأفراد الأسرة والعمالة المنزلية) أو أبشر أعمال (لعمالة المنشآت). يمكن التجديد بمدد تبدأ من 3 أشهر.",
    url: "https://www.absher.sa/wps/vanityurl/ar/guide/Renewal-of-residence-permit",
    requirements: [
      {
        id: "iq-insurance",
        label: "تأمين صحي ساري للعامل وأفراد أسرته",
        kind: "document",
        obtain: { title: "إصدار وثيقة تأمين صحي", steps: ["التواصل مع شركة تأمين معتمدة من هيئة التأمين", "إصدار الوثيقة وربطها بمجلس الضمان الصحي", "التحقق من ظهورها في أبشر"], why: "التأمين الصحي شرط نظامي لتجديد الإقامة." },
      },
      { id: "iq-passport", label: "جواز سفر ساري", kind: "document" },
      { id: "iq-fees", label: "سداد رسوم الإقامة (600 ريال عمالة منزلية / 500 ريال فرد أسرة 18+) والمقابل المالي للمرافقين", kind: "condition" },
      { id: "iq-violations", label: "عدم وجود مخالفات مرورية غير مسددة", kind: "condition" },
      { id: "iq-biometrics", label: "بصمة وصورة مسجلة (لمن فوق 6 سنوات)", kind: "condition" },
      { id: "iq-not-expired", label: "ألا تكون الإقامة منتهية منذ أكثر من 6 أشهر", kind: "condition" },
      { id: "iq-work-permit", label: "رخصة عمل سارية (لعمالة المنشآت)", kind: "document", description: "تُصدر عبر وزارة الموارد البشرية (100 ريال)." },
    ],
    prerequisites: [],
    steps: [
      "سداد رسوم الإقامة والمقابل المالي عبر المدفوعات الحكومية",
      "الدخول إلى أبشر (أفراد أو أعمال)",
      "خدمات المقيمين → تجديد هوية مقيم",
      "اختيار المستفيد والمدة والتأكيد",
    ],
    fees: "600 ريال (عمالة منزلية) / 500 ريال (فرد أسرة 18+) + المقابل المالي للمرافقين",
    duration: "فوري",
    sources: ["https://www.absher.sa/wps/vanityurl/ar/guide/Renewal-of-residence-permit", "https://my.gov.sa/ar/services/487325", "https://my.gov.sa/ar/services/19034"],
    keywords: ["إقامة", "اقامة", "تجديد الإقامة", "مقيم", "هوية مقيم"],
    lastVerified: VERIFIED,
  },
  {
    id: "driving-license",
    name: "إصدار رخصة قيادة (خصوصي)",
    entityId: "muroor",
    category: "traffic",
    description: "إصدار رخصة قيادة خاصة لأول مرة: حجز موعد في مدرسة تعليم قيادة معتمدة عبر أبشر، فحص طبي، ثم اجتياز التدريب والاختبارات.",
    url: "https://www.absher.sa",
    requirements: [
      { id: "dl-age", label: "العمر 18 عاماً فأكثر", kind: "condition" },
      { id: "dl-absher", label: "حساب أبشر مفعّل", kind: "condition", obtain: ABSHER_OBTAIN },
      {
        id: "dl-medical",
        label: "فحص طبي من مركز طبي معتمد",
        kind: "document",
        obtain: { title: "إجراء الفحص الطبي لرخصة القيادة", steps: ["زيارة مركز طبي معتمد لفحص رخص القيادة", "إجراء فحص النظر والفحوصات المطلوبة", "رفع النتيجة إلكترونياً إلى نظام المرور"], durationText: "يوم واحد", why: "الفحص الطبي شرط نظامي لإصدار الرخصة." },
      },
      {
        id: "dl-school",
        label: "حجز موعد واجتياز اختبارات مدرسة تعليم القيادة",
        kind: "condition",
        obtain: { title: "التسجيل في مدرسة تعليم القيادة", entityId: "muroor", url: "https://www.absher.sa", steps: ["أبشر → المرور → إصدار رخصة القيادة", "اختيار مدرسة القيادة وحجز الموعد", "إتمام التدريب واجتياز الاختبار النظري والعملي"], why: "اجتياز الاختبارات شرط للإصدار." },
      },
      { id: "dl-fees", label: "سداد رسوم الإصدار (40 ريال لكل سنة)", kind: "condition" },
    ],
    prerequisites: [],
    steps: [
      "الدخول إلى أبشر → خدماتي → المرور → إصدار رخصة القيادة",
      "اختيار مدرسة تعليم القيادة وحجز الموعد",
      "إجراء الفحص الطبي في مركز معتمد",
      "إتمام التدريب واجتياز الاختبارات",
      "سداد الرسوم وإصدار الرخصة (رقمية عبر أبشر/توكلنا)",
    ],
    fees: "40 ريال لكل سنة + رسوم مدرسة القيادة",
    duration: "4 أيام عمل بعد اجتياز الاختبارات",
    sources: ["https://my.gov.sa/ar/services/112124", "https://www.absher.sa/wps/vanityurl/ar/guide/Driving-License-Renewal"],
    keywords: ["رخصة قيادة", "قيادة", "رخصة", "مرور", "سواقة", "اسوق", "أسوق"],
    lastVerified: VERIFIED,
  },
  {
    id: "vehicle-registration",
    name: "تجديد رخصة السير / مبايعة مركبة",
    entityId: "muroor",
    category: "traffic",
    description: "تجديد استمارة المركبة (100 ريال لكل سنة) أو نقل ملكيتها بين الأفراد عبر خدمة المبايعة في أبشر (230 ريال أجور الخدمة + الرسوم الحكومية).",
    url: "https://www.absher.sa/vot",
    requirements: [
      {
        id: "vr-inspection",
        label: "شهادة الفحص الدوري (الفني) سارية",
        kind: "document",
        obtain: { title: "حجز موعد الفحص الفني الدوري", url: "https://my.gov.sa/ar/services/252246", steps: ["الدخول إلى المنصة الموحدة لمواعيد الفحص الفني الدوري", "حجز موعد في أقرب مركز فحص", "اجتياز الفحص والحصول على الشهادة"], durationText: "يوم واحد", why: "الفحص الدوري شرط لتجديد رخصة السير ونقل الملكية." },
      },
      {
        id: "vr-insurance",
        label: "وثيقة تأمين سارية على المركبة",
        kind: "document",
        obtain: { title: "شراء وثيقة تأمين للمركبة", steps: ["اختيار شركة تأمين معتمدة", "إصدار وثيقة تأمين ضد الغير أو شامل", "التحقق من ربطها بنظام المرور"], durationText: "فوري", why: "التأمين شرط نظامي لتجديد الاستمارة وإتمام المبايعة." },
      },
      { id: "vr-violations", label: "سداد المخالفات المرورية", kind: "condition" },
      { id: "vr-fees", label: "سداد الرسوم عبر سداد", kind: "condition" },
      { id: "vr-bank", label: "حساب بنكي مرتبط (للمبايعة)", kind: "condition", description: "للبائع والمشتري عند نقل الملكية." },
    ],
    prerequisites: [],
    steps: [
      "الدخول إلى أبشر → خدمات المركبات",
      "تجديد رخصة سير: اختيار المركبة → تحقق آلي → تأكيد التجديد",
      "مبايعة: البائع يُدخل بيانات المشتري والثمن → المشتري يقبل خلال ساعة ويدفع",
      "تأمين المركبة باسم المشتري قبل إتمام النقل",
      "سداد الرسوم الحكومية ورسوم أبشر → نقل الملكية رسمياً",
    ],
    fees: "تجديد: 100 ريال/سنة · مبايعة: 230 ريال أجور خدمة + رسوم حكومية",
    duration: "فوري",
    sources: ["https://my.gov.sa/ar/services/112111", "https://my.gov.sa/ar/services/112114", "https://my.gov.sa/ar/services/252246"],
    keywords: ["استمارة", "سيارة", "سيارتي", "مركبة", "نقل ملكية", "تجديد استمارة", "فحص دوري", "مبايعة"],
    lastVerified: VERIFIED,
  },
  {
    id: "birth-registration",
    name: "تسجيل مولود (شهادة الميلاد)",
    entityId: "ahwal",
    category: "civil",
    description: "تسجيل المولود إلكترونياً عبر أبشر بعد تبليغ الولادة من المستشفى، وإصدار شهادة الميلاد وتحديث سجل الأسرة. المواطن: خلال 30 يوماً بدون غرامة (حتى 360 يوماً). المقيم: خلال 30 يوماً.",
    url: "https://www.absher.sa/wps/vanityurl/ar/guide/Register-Newborn-Service",
    requirements: [
      { id: "br-hospital", label: "تبليغ ولادة مسجل في نظام وزارة الصحة", kind: "document", description: "يصدره المستشفى عند الولادة داخل المملكة." },
      { id: "br-absher", label: "حساب أبشر مفعّل لولي الأمر", kind: "condition", obtain: ABSHER_OBTAIN },
      { id: "br-address", label: "عنوان وطني للتوصيل", kind: "document", obtain: NATIONAL_ADDRESS_OBTAIN },
      { id: "br-fines", label: "سداد غرامات الأحوال المدنية إن وجدت", kind: "condition" },
      { id: "br-delivery", label: "سداد أجور التوصيل (39.91 ريال)", kind: "condition" },
    ],
    prerequisites: [],
    steps: [
      "الدخول إلى أبشر → خدمات الأحوال المدنية → تسجيل المواليد",
      "اختيار المولود وتأكيد البيانات",
      "اختيار عنوان التوصيل ودفع الأجور",
      "حفظ الرقم المرجعي واستلام شهادة الميلاد وسجل الأسرة المحدث",
    ],
    fees: "مجاناً + أجور توصيل 39.91 ريال",
    duration: "فوري",
    sources: ["https://my.gov.sa/ar/services/112099", "https://www.absher.sa/wps/vanityurl/ar/guide/Register-Newborn-Service", "https://my.gov.sa/ar/services/112102"],
    keywords: ["مولود", "ولادة", "شهادة ميلاد", "طفل", "بيبي", "رزقنا"],
    lastVerified: VERIFIED,
  },
  {
    id: "family-visit-visa",
    name: "طلب تأشيرة زيارة عائلية",
    entityId: "mofa",
    category: "passports",
    description: "طلب زيارة عائلية للأقارب من الدرجة الأولى عبر منصة التأشيرات (وزارة الخارجية)، مع تصديق النموذج من جهة العمل أو الغرفة التجارية.",
    url: "https://visa.mofa.gov.sa/Home/Services/citizens",
    requirements: [
      { id: "fv-iqama", label: "إقامة عمل سارية لمقدم الطلب", kind: "document" },
      { id: "fv-passport", label: "جواز سفر الزائر ساري 6 أشهر على الأقل", kind: "document" },
      { id: "fv-photo", label: "صورة شخصية للزائر بخلفية بيضاء", kind: "document" },
      {
        id: "fv-insurance",
        label: "وثيقة تأمين طبي تغطي مدة الزيارة",
        kind: "document",
        obtain: { title: "شراء تأمين طبي للزائر", steps: ["اختيار شركة تأمين معتمدة", "إصدار وثيقة تأمين زيارة تغطي كامل المدة"], why: "التأمين الصحي شرط للتأشيرة ولتمديدها." },
      },
      { id: "fv-relation", label: "إثبات صلة القرابة (قيد عائلي / شهادة ميلاد / عقد زواج مصدق)", kind: "document" },
      {
        id: "fv-attest",
        label: "تصديق النموذج من جهة العمل أو الغرفة التجارية",
        kind: "document",
        obtain: { title: "تصديق طلب الزيارة", steps: ["طباعة النموذج من منصة التأشيرات", "التصديق من جهة العمل أو الغرفة التجارية", "رفعه في المنصة"], why: "المنصة تشترط مصادقة النموذج من جهة العمل." },
      },
      { id: "fv-fees", label: "سداد الرسوم (300 ريال)", kind: "condition" },
    ],
    prerequisites: [],
    steps: [
      "الدخول إلى منصة التأشيرات → خدمات المواطنين والمقيمين → طلب زيارة عائلية",
      "إدخال بيانات مقدم الطلب والزائرين كما في الجواز",
      "إرفاق المستندات ومراجعة الطلب وإرساله",
      "تصديق النموذج من جهة العمل / الغرفة التجارية",
      "موافقة الخارجية وإصدار رقم التأشيرة، ثم استكمال الزائر إجراءات السفارة",
    ],
    fees: "300 ريال",
    duration: "3 إلى 5 أيام عمل",
    sources: ["https://my.gov.sa/ar/services/18563", "https://www.mofa.gov.sa/ar/eservices/pages/svc13.aspx", "https://my.gov.sa/ar/services/269236"],
    keywords: ["زيارة", "تأشيرة", "زيارة عائلية", "فيزا", "اجيب اهلي", "أجيب أهلي"],
    lastVerified: VERIFIED,
  },
  {
    id: "ejar-residential",
    name: "توثيق عقد إيجار سكني",
    entityId: "ejar",
    category: "housing",
    description: "تسجيل وتوثيق عقد إيجار السكن عبر منصة إيجار (125 ريال لكل سنة). يُسجَّل عبر الوسيط العقاري ويعتمده الطرفان إلكترونياً. للمقيمين: العقد الموثق شرط لإصدار/تجديد رخصة العمل.",
    url: "https://www.ejar.sa/ar/service/188274",
    requirements: [
      { id: "ejr-id", label: "هوية سارية للمؤجر والمستأجر ورقم جوال مسجل في أبشر", kind: "document" },
      { id: "ejr-property", label: "وثائق ملكية العقار (لدى المؤجر)", kind: "document" },
      { id: "ejr-broker", label: "وسيط عقاري معتمد (رخصة فال)", kind: "condition" },
      { id: "ejr-iban", label: "حساب بنكي للمؤجر (إن كان السداد عبر سداد)", kind: "document" },
      { id: "ejr-fees", label: "رسوم التوثيق: 125 ريال لكل سنة", kind: "condition" },
    ],
    prerequisites: [],
    steps: [
      "تسجيل العقد من حساب المكتب العقاري في إيجار",
      "إدخال مدة العقد وبيانات العقار والوحدة والأطراف",
      "البيانات المالية والشروط والأحكام",
      "إرسال العقد للأطراف للموافقة إلكترونياً",
      "دفع الرسوم والتوثيق",
    ],
    fees: "125 ريال لكل سنة",
    duration: "فوري بعد موافقة الطرفين",
    sources: ["https://my.gov.sa/ar/services/263274", "https://www.ejar.sa/ar/service/188274", "https://www.ejar.sa/ar/faqregulation"],
    keywords: ["سكن", "شقة", "عقد سكني", "إيجار سكني", "ايجار", "استاجر", "أستأجر", "بيت"],
    lastVerified: VERIFIED,
  },
  {
    id: "national-address",
    name: "التسجيل في العنوان الوطني",
    entityId: "spl",
    category: "civil",
    description: "تسجيل العنوان الوطني للأفراد مجاناً عبر منصة العنوان الوطني (سبل) بالنفاذ الوطني. شرط مسبق لخدمات التوصيل في أبشر ولمعظم الخدمات الحكومية.",
    url: "https://register.address.gov.sa/ar/individual/",
    requirements: [
      { id: "na-id", label: "هوية وطنية أو هوية مقيم", kind: "document" },
      { id: "na-nafath", label: "حساب النفاذ الوطني الموحد", kind: "condition", obtain: ABSHER_OBTAIN },
    ],
    prerequisites: [],
    steps: ["الدخول إلى صفحة تسجيل الأفراد", "الموافقة على الشروط والدخول عبر النفاذ الوطني", "تعبئة بيانات العنوان والتسجيل", "استلام الرمز المختصر (4 حروف + 4 أرقام)"],
    fees: "مجاناً",
    duration: "فوري (التفعيل خلال 24 ساعة)",
    sources: ["https://my.gov.sa/ar/services/182790", "https://splonline.com.sa/ar/services-catalogue/servicenew03", "https://register.address.gov.sa/ar/individual/"],
    keywords: ["عنوان وطني", "عنوان", "سبل", "بريد"],
    lastVerified: VERIFIED,
  },
  {
    id: "sehhaty-appointment",
    name: "حجز موعد طبي عبر صحتي",
    entityId: "moh",
    category: "health",
    description: "حجز موعد في مركز الرعاية الصحية الأولية عبر تطبيق صحتي مجاناً، مع إمكانية عرض التقارير الطبية والإجازات المرضية.",
    url: "https://www.moh.gov.sa/eServices/cards/Pages/Appointment-Booking-service.aspx",
    requirements: [
      { id: "sh-account", label: "حساب في تطبيق صحتي (الدخول عبر النفاذ الوطني)", kind: "condition", obtain: { title: "تحميل تطبيق صحتي وإنشاء حساب", url: "https://www.moh.gov.sa", steps: ["تحميل تطبيق صحتي من المتجر", "تسجيل الدخول عبر النفاذ الوطني", "إكمال الملف الصحي"], durationText: "دقائق", why: "المواعيد والتقارير الطبية تُدار من داخل تطبيق صحتي." } },
    ],
    prerequisites: [],
    steps: ["الدخول إلى صحتي → المواعيد → حجز موعد", "اختيار المركز الصحي والخدمة والتاريخ والوقت", "استلام رسالة التأكيد", "المتابعة أو إعادة الجدولة من «مواعيدي»"],
    fees: "مجاناً",
    duration: "فوري",
    sources: ["https://my.gov.sa/ar/services/237229", "https://www.moh.gov.sa/eServices/cards/Pages/Appointment-Booking-service.aspx", "https://www.moh.gov.sa/en/eservices/cards/pages/medical-reports-sick-leaves.aspx"],
    keywords: ["موعد", "مركز صحي", "صحتي", "طبيب", "دكتور", "مستشفى", "تقرير طبي"],
    lastVerified: VERIFIED,
  },
  {
    id: "social-security",
    name: "التقديم على الضمان الاجتماعي المطور",
    entityId: "hrsd",
    category: "social",
    description: "التقديم على معاش الضمان الاجتماعي المطور عبر منصة الدعم والحماية الاجتماعية للأسر والمستقلين الذين يقل دخلهم عن الحد الأدنى المحتسب.",
    url: "https://sbis.hrsd.gov.sa/",
    requirements: [
      { id: "ss-citizen", label: "سعودي مقيم إقامة دائمة (مع استثناءات محددة)", kind: "condition", description: "مثل المرأة غير السعودية المتزوجة من سعودي، وأبناء السعودية من زوج غير سعودي." },
      { id: "ss-income", label: "الدخل المحتسب أقل من الحد الأدنى للمعاش", kind: "condition" },
      { id: "ss-iban", label: "حساب بنكي (IBAN) باسم مقدم الطلب", kind: "document", obtain: { title: "فتح حساب بنكي", steps: ["زيارة أي بنك محلي أو فتح حساب رقمي", "الحصول على رقم IBAN"], why: "صرف المعاش يتم على الحساب البنكي." } },
      { id: "ss-family", label: "بيانات الأسرة والدخل والعائل", kind: "condition" },
      { id: "ss-docs", label: "المستندات المطلوبة حسب فئة المستفيد", kind: "document", description: "تظهر في المنصة حسب الفئة (شيخوخة، أرملة، مطلقة، عاجز عن العمل...)." },
    ],
    prerequisites: [],
    steps: [
      "إنشاء مستخدم جديد في منصة الدعم والحماية الاجتماعية والتوثيق",
      "تعبئة بيانات الطلب (الأسرة، الدخل، الحساب البنكي)",
      "إرفاق المستندات وتقديم الطلب",
      "متابعة الطلب من «طلباتي» (الرد خلال 20 إلى 25 يوم عمل)",
    ],
    fees: "مجاناً",
    duration: "حتى 25 يوم عمل",
    sources: ["https://my.gov.sa/ar/services/19820", "https://www.hrsd.gov.sa/ar/ministry-services/services/نظام-الضمان-الاجتماعي-المطور", "https://sbis.hrsd.gov.sa/"],
    keywords: ["ضمان", "ضمان اجتماعي", "معاش", "دعم", "مساعدة مالية", "محتاج دعم"],
    lastVerified: VERIFIED,
  },
  {
    id: "disability-card",
    name: "خدمات ذوي الإعاقة (تقييم الإعاقة وبطاقة تسهيلات)",
    entityId: "hrsd",
    category: "social",
    description: "تقييم الإعاقة لدى وزارة الموارد البشرية هو المتطلب الأساسي، ثم تُتاح بطاقة «تسهيلات» والشهادة الرقمية للتسهيلات المرورية ومشهد الإعاقة إلكترونياً.",
    url: "https://my.gov.sa/ar/services/18476",
    requirements: [
      {
        id: "dc-assessment",
        label: "تقييم إعاقة ساري لدى الوزارة",
        kind: "document",
        obtain: { title: "طلب خدمة تقييم الإعاقة", entityId: "hrsd", url: "https://www.hrsd.gov.sa/ar/ministry-services/services/خدمة-تقييم-الإعاقة", steps: ["تعبئة البيانات الاجتماعية وبيانات ولي الأمر", "إرفاق التقارير الطبية", "الإقرار وتقديم الطلب", "المتابعة من «طلباتي»"], durationText: "30 يوماً", why: "جميع خدمات ذوي الإعاقة تعتمد على تقييم إعاقة ساري." },
      },
      { id: "dc-reports", label: "تقارير طبية حديثة", kind: "document" },
    ],
    prerequisites: [],
    steps: ["طلب تقييم الإعاقة عبر الوزارة", "بعد الاعتماد: إصدار الشهادة الرقمية للتسهيلات المرورية أو مشهد الإعاقة", "الاستفادة من بطاقة تسهيلات عبر توكلنا خدمات"],
    fees: "مجاناً",
    duration: "التقييم 30 يوماً، الشهادات فورية",
    sources: ["https://my.gov.sa/ar/services/18476", "https://my.gov.sa/ar/services/19424", "https://www.hrsd.gov.sa/media-center/news/1170345"],
    keywords: ["إعاقة", "اعاقة", "ذوي الإعاقة", "تسهيلات", "بطاقة إعاقة"],
    lastVerified: VERIFIED,
  },
];
