import type { Service } from "@/lib/types";

/**
 * خدمات الأعمال — تم التحقق من المحتوى من المصادر الحكومية الرسمية بتاريخ 2026-09-12.
 * التفاصيل الكاملة والروابط: docs/research-business.md
 */
const VERIFIED = "2026-09-12";

export const BUSINESS_SERVICES: Service[] = [
  {
    id: "commercial-register",
    name: "قيد سجل تجاري لمؤسسة فردية",
    entityId: "sbc",
    category: "business",
    description:
      "إصدار سجل تجاري عبر منصة المركز السعودي للأعمال. وفق النظام الجديد (نافذ من 3 أبريل 2025): سجل واحد لكل الأنشطة على مستوى المملكة بدون تاريخ انتهاء، مع تأكيد سنوي للبيانات.",
    url: "https://business.sa/ar/eservices/details/ee829025-1253-41d3-f9fc-08dd6ab9228a",
    requirements: [
      {
        id: "cr-national-id",
        label: "هوية وطنية سارية وعمر 18 سنة فأكثر",
        kind: "condition",
        description: "الخدمة للسعوديين والخليجيين، بشرط ألا يكون مقدم الطلب موظفاً حكومياً.",
        obtain: {
          title: "تجديد الهوية الوطنية عبر أبشر",
          entityId: "ahwal",
          serviceId: "national-id-renew",
          url: "https://www.absher.sa",
          steps: ["الدخول إلى أبشر أفراد", "خدمات الأحوال المدنية", "تجديد الهوية الوطنية"],
          why: "لا يمكن إصدار سجل تجاري بهوية منتهية الصلاحية.",
        },
      },
      {
        id: "cr-absher",
        label: "حساب النفاذ الوطني الموحد (أبشر) فعّال",
        kind: "condition",
        description: "الدخول إلى منصة المركز السعودي للأعمال يتم عبر النفاذ الوطني.",
        obtain: {
          title: "تفعيل حساب أبشر",
          entityId: "ahwal",
          url: "https://www.absher.sa",
          steps: ["التسجيل في أبشر أفراد", "تفعيل الحساب عبر أجهزة الخدمة الذاتية أو البنك", "تسجيل الدخول عبر النفاذ الوطني"],
          why: "جميع خدمات المركز السعودي للأعمال تتطلب النفاذ الوطني الموحد.",
        },
      },
      {
        id: "cr-no-other",
        label: "عدم امتلاك سجل مؤسسة فردية نشط آخر",
        kind: "condition",
        description: "النظام الجديد يسمح بمؤسسة فردية واحدة لكل شخص تُمارس عبرها جميع الأنشطة.",
      },
      {
        id: "cr-trade-name",
        label: "اسم تجاري (يُحجز قبل القيد)",
        kind: "condition",
        description: "يُسمح بأسماء عربية أو معرّبة أو بأحرف لاتينية وأرقام. الحجز قابل للتجديد مرة واحدة.",
        obtain: {
          title: "حجز اسم تجاري",
          entityId: "sbc",
          url: "https://business.sa",
          steps: ["الدخول إلى منصة المركز السعودي للأعمال", "خدمة حجز اسم تجاري", "اقتراح اسم والتحقق من توفره"],
          durationText: "فوري",
          why: "السجل التجاري يصدر باسم تجاري معتمد ومحجوز.",
        },
      },
      {
        id: "cr-activity",
        label: "تحديد النشاط التجاري",
        kind: "condition",
        description: "اختيار الأنشطة من دليل الأنشطة الاقتصادية. بعض الأنشطة تتطلب موافقة الجهة المرخِّصة أولاً.",
      },
      {
        id: "cr-license-approval",
        label: "موافقة الجهة المرخِّصة (إن كان النشاط يتطلب ترخيصاً مسبقاً)",
        kind: "document",
        description: "مثال: الأنشطة الصحية أو الغذائية أو السياحية.",
      },
      {
        id: "cr-fees",
        label: "سداد الرسوم: 500 ريال",
        kind: "condition",
        description: "الدفع عبر سداد أو البطاقة البنكية عند إصدار الفاتورة.",
      },
    ],
    prerequisites: [],
    steps: [
      "الدخول عبر النفاذ الوطني الموحد إلى منصة المركز السعودي للأعمال",
      "الخدمات الإلكترونية > قيد سجل تجاري > نوع السجل «مؤسسة»",
      "مراجعة الشروط والموافقة، وتعبئة بيانات المالك وعنوان الأعمال",
      "اختيار الأنشطة، وتحديد رأس المال، وتكوين الاسم التجاري",
      "إدخال عنوان المؤسسة وتعيين المدير",
      "مراجعة الملخص والموافقة على الإقرار وتقديم الطلب",
      "إصدار الفاتورة والدفع (500 ريال) → يصدر السجل فوراً",
      "التسجيل التلقائي في: الموارد البشرية، الزكاة والضريبة، التأمينات، العنوان الوطني، الغرفة التجارية",
    ],
    fees: "500 ريال",
    duration: "فوري",
    sources: [
      "https://my.gov.sa/ar/services/240897",
      "https://business.sa/ar/eservices/details/ee829025-1253-41d3-f9fc-08dd6ab9228a",
      "https://mc.gov.sa/ar/eservices/Pages/ServiceDetails.aspx?sID=38",
      "https://mc.gov.sa/ar/mediacenter/News/Pages/03-04-25-01.aspx",
    ],
    keywords: ["سجل تجاري", "سجل", "مؤسسة", "شركة", "مشروع", "تجارة", "محل", "نشاط تجاري", "قيد"],
    lastVerified: VERIFIED,
  },
  {
    id: "balady-license",
    name: "إصدار رخصة نشاط تجاري (بلدي)",
    entityId: "balady",
    category: "business",
    description:
      "رخصة مزاولة النشاط للمحل من أمانة منطقة الحدود الشمالية عبر منصة بلدي. تشمل الرخصة تصريح السلامة من الدفاع المدني للأنشطة المعتمدة دون مراجعة الجهة.",
    url: "https://balady.gov.sa/en/services/issuing-commercial-license",
    requirements: [
      {
        id: "bl-lease",
        label: "عقد إيجار موثق (أو صك ملكية / عقد استثمار)",
        kind: "document",
        description: "عقد إيجار تجاري إلكتروني موثق عبر منصة إيجار للمحل.",
        obtain: {
          title: "توثيق عقد إيجار تجاري في منصة إيجار",
          entityId: "ejar",
          serviceId: "ejar-commercial",
          url: "https://www.ejar.sa/ar/page/1394",
          steps: [
            "الاتفاق مع المؤجر على المحل",
            "التوجه إلى مكتب وساطة عقارية معتمد (التسجيل يتم عبر حساب الوسيط)",
            "إدخال بيانات العقار والأطراف والبيانات المالية",
            "سداد المقابل المالي (200 ريال لكل سنة)",
            "توثيق العقد من المؤجر والمستأجر عبر روابط SMS",
          ],
          durationText: "فوري بعد اعتماد الطرفين",
          why: "منصة بلدي تشترط عقد إيجار أو صك ملكية أو عقد استثمار لإثبات موقع النشاط.",
        },
      },
      {
        id: "bl-photo",
        label: "صورة خارجية للمحل تظهر فيها اللوحة",
        kind: "document",
      },
      {
        id: "bl-safety",
        label: "فاتورة أدوات السلامة أو تقرير سلامة من الدفاع المدني",
        kind: "document",
        obtain: {
          title: "توفير أدوات السلامة عبر مقاول معتمد",
          url: "https://balady.gov.sa/ar/node/10856",
          steps: ["الاستعلام عن اشتراطات النشاط في بلدي", "تركيب أدوات السلامة المطلوبة", "الحصول على فاتورة من مورد/مقاول معتمد"],
          why: "الرخصة تُصدر تصريح السلامة تلقائياً بناءً على استيفاء أدوات السلامة.",
        },
      },
      {
        id: "bl-building-license",
        label: "نسخة من رخصة البناء",
        kind: "document",
        description: "تُطلب من مالك العقار.",
      },
      {
        id: "bl-compliance",
        label: "النشاط معتمد ومطابق لاشتراطات البلدية",
        kind: "condition",
        description: "تختلف الاشتراطات حسب النشاط؛ راجع خدمة «الاستعلام عن اشتراطات الأنشطة البلدية».",
      },
    ],
    prerequisites: ["commercial-register"],
    steps: [
      "الدخول إلى منصة بلدي (الموقع أو التطبيق) عبر النفاذ الوطني",
      "إدخال السجل التجاري وتحديد النشاط والمساحة",
      "تحديد الموقع وتعبئة تفاصيل المحل",
      "إرفاق المستندات (عقد الإيجار، الصورة، فاتورة السلامة)",
      "دفع الرسوم للأنشطة الفورية، أو إرسال الطلب للبلدية للأنشطة غير الفورية",
    ],
    fees: "حسب النشاط والموقع (حاسبة الرسوم في بلدي)",
    duration: "1 إلى 10 أيام عمل (الأنشطة الفورية فور الدفع)",
    sources: [
      "https://balady.gov.sa/en/services/issuing-commercial-license",
      "https://my.gov.sa/ar/services/19208",
      "https://momah.gov.sa/en/e-services/issuing-commercial-license",
      "https://balady.gov.sa/en/node/10856",
      "https://balady.gov.sa/ar/node/11754",
    ],
    keywords: ["رخصة بلدية", "رخصة", "بلدي", "محل", "أمانة", "رخصة تجارية", "رخصة نشاط"],
    lastVerified: VERIFIED,
  },
  {
    id: "ejar-commercial",
    name: "توثيق عقد إيجار تجاري",
    entityId: "ejar",
    category: "housing",
    description:
      "تسجيل وتوثيق عقد إيجار المحل أو المكتب إلكترونياً عبر شبكة إيجار. العقد الموحد سند تنفيذي ومقبول لدى بلدي والجهات الحكومية.",
    url: "https://www.ejar.sa/ar/page/1394",
    requirements: [
      { id: "ej-broker", label: "مكتب وساطة عقارية معتمد", kind: "condition", description: "التسجيل يتم عبر حساب الوسيط العقاري في إيجار." },
      { id: "ej-parties", label: "هوية وطنية/إقامة الأطراف ورقم جوال فعّال", kind: "document" },
      { id: "ej-cr", label: "رقم السجل التجاري للمنشأة المستأجرة", kind: "document" },
      { id: "ej-property", label: "بيانات العقار والوحدة", kind: "document" },
      { id: "ej-iban", label: "IBAN المؤجر", kind: "document" },
      { id: "ej-fees", label: "المقابل المالي: 200 ريال عن كل سنة", kind: "condition", description: "أجزاء السنة تُحسب سنة كاملة." },
    ],
    prerequisites: [],
    steps: [
      "من حساب المكتب العقاري: قائمة العقود → تسجيل عقد إيجار تجاري",
      "تحديد مدة العقد وإضافة العقار والوحدة",
      "إدخال أطراف العقد (المؤجر والمستأجر/المنشأة)",
      "البيانات المالية: قيمة الإيجار، دورة السداد، IBAN",
      "معاينة العقد ودفع المقابل المالي",
      "توثيق العقد من الطرفين عبر روابط SMS",
    ],
    fees: "200 ريال لكل سنة تعاقدية",
    duration: "فوري",
    sources: ["https://my.gov.sa/ar/services/263385", "https://www.ejar.sa/ar/page/1394", "https://www.ejar.sa/ar/help/user-manual/236009"],
    keywords: ["عقد إيجار", "ايجار", "إيجار", "محل", "مكتب", "عقد تجاري"],
    lastVerified: VERIFIED,
  },
  {
    id: "final-permit",
    name: "التراخيص التخصصية حسب النشاط",
    entityId: "sbc",
    category: "business",
    description: "بعض الأنشطة تتطلب ترخيصاً من جهة مختصة (مثل الغذاء والدواء، السياحة، الصحة). يُحدد ذلك من دليل الأنشطة في المركز السعودي للأعمال.",
    url: "https://business.sa",
    requirements: [
      { id: "fp-activity-license", label: "ترخيص الجهة المختصة بالنشاط (إن وجد)", kind: "document", description: "يُستعلم عنه من دليل الأنشطة والاشتراطات." },
    ],
    prerequisites: ["balady-license"],
    steps: ["التحقق من اشتراطات النشاط في دليل الأنشطة", "التقديم على الترخيص التخصصي عبر الجهة المختصة", "ربط الترخيص بالسجل التجاري"],
    fees: "حسب الجهة",
    duration: "حسب الجهة",
    sources: ["https://business.sa/servicesprocedures/details/9c24a1e9-659f-4b0c-ef45-08dced12ee80"],
    keywords: ["ترخيص", "تراخيص", "نشاط"],
    lastVerified: VERIFIED,
  },
  {
    id: "zatca-register",
    name: "التسجيل في الزكاة وضريبة القيمة المضافة",
    entityId: "zatca",
    category: "tax",
    description:
      "بعد إصدار السجل التجاري يُنشأ رقم مميز للمنشأة ويُسجَّل المكلف استباقياً في الزكاة. التسجيل في ضريبة القيمة المضافة إلزامي عند تجاوز الإيرادات 375,000 ريال سنوياً واختياري بين 187,500 و375,000 ريال.",
    url: "https://zatca.gov.sa",
    requirements: [
      { id: "zt-cr", label: "سجل تجاري (رقم مميز للمنشأة)", kind: "document" },
      { id: "zt-account", label: "حساب مكلف في بوابة الهيئة", kind: "condition" },
      { id: "zt-threshold", label: "تجاوز حد التسجيل الإلزامي (375,000 ريال) أو الرغبة في التسجيل الاختياري", kind: "condition" },
    ],
    prerequisites: ["commercial-register"],
    steps: [
      "إكمال التسجيل لدى وزارة التجارة (السجل التجاري)",
      "تسجيل الدخول إلى بوابة الهيئة الإلكترونية وإكمال التسجيل الأولي في الزكاة",
      "الخدمات العامة → التسجيل في ضريبة القيمة المضافة",
      "تعبئة نموذج التسجيل",
      "استلام رقم الحساب الضريبي عبر SMS والبريد",
    ],
    fees: "مجاناً",
    duration: "التسجيل في الزكاة فوري",
    sources: [
      "https://my.gov.sa/ar/services/19160",
      "https://zatca.gov.sa/en/eServices/Pages/eServices-001.aspx",
      "https://zatca.gov.sa/en/eServices/Pages/eServices_002.aspx",
    ],
    keywords: ["ضريبة", "زكاة", "القيمة المضافة", "رقم ضريبي", "زاتكا"],
    lastVerified: VERIFIED,
  },
  {
    id: "gosi-register",
    name: "تسجيل المنشأة في التأمينات الاجتماعية",
    entityId: "gosi",
    category: "labor",
    description:
      "فتح اشتراك للمنشأة وتسجيل الموظفين. يشترط تسجيل بيانات المنشأة لدى وزارة الموارد البشرية أولاً (يتم تلقائياً مع السجل التجاري)، وتقديم الطلب خلال أسبوعين من استكمال شروط الخضوع.",
    url: "https://www.gosi.gov.sa/GOSIOnline/Registration",
    requirements: [
      { id: "gs-cr", label: "سجل تجاري", kind: "document" },
      { id: "gs-hrsd", label: "ملف المنشأة لدى وزارة الموارد البشرية", kind: "document", description: "يُفتح تلقائياً مع السجل التجاري؛ وإن لم يظهر يُفتح عبر خدمة «فتح ملف منشأة».",
        obtain: { title: "فتح ملف منشأة في وزارة الموارد البشرية", entityId: "hrsd", url: "https://my.gov.sa/ar/services/19274", steps: ["اختيار خدمة فتح ملف منشأة", "إدخال نوع المنشأة والنشاط ومكتب العمل", "إدخال العنوان وإرسال الطلب"], durationText: "فوري", why: "التأمينات تشترط تسجيل المنشأة لدى الوزارة قبل فتح الاشتراك." } },
    ],
    prerequisites: ["commercial-register"],
    steps: ["الدخول إلى تأمينات أون لاين", "اختيار «تسجيل منشأة جديدة»", "إكمال بيانات المنشأة", "اختيار مشرف المنشأة", "حفظ وإرسال الطلب"],
    fees: "مجاناً",
    duration: "فوري إلى يوم عمل",
    sources: ["https://my.gov.sa/ar/services/25073", "https://www.gosi.gov.sa/GOSIOnline/Registration", "https://www.gosi.gov.sa/GOSIOnline/FAQ_Employer"],
    keywords: ["تأمينات", "موظفين", "اشتراك", "التأمينات الاجتماعية"],
    lastVerified: VERIFIED,
  },
  {
    id: "qiwa-establishment",
    name: "تسجيل المنشأة في منصة قوى",
    entityId: "qiwa",
    category: "labor",
    description:
      "تُسجَّل المنشأة تلقائياً في قوى بمجرد صدور الرقم الوطني الموحد من الجهة المرخصة. يجب اشتراك مجموعة المنشآت في قوى لاستخدام الخدمات (التأشيرات، العقود، نقل الخدمات).",
    url: "https://qiwa.sa/ar/business-owners/create-new-establishment/how-register-new-establishment-qiwa",
    requirements: [
      { id: "qw-cr", label: "الرقم الوطني الموحد للمنشأة (السجل التجاري)", kind: "document" },
      { id: "qw-manager", label: "صلاحية مدير المجموعة (مالك المنشأة)", kind: "condition" },
      { id: "qw-subscription", label: "اشتراك مجموعة المنشآت في قوى", kind: "condition" },
    ],
    prerequisites: ["commercial-register", "gosi-register"],
    steps: [
      "تسجيل الدخول إلى حساب قوى أعمال",
      "حسابات المنشآت → «تسجيل منشأة جديدة» (إن لم تظهر تلقائياً)",
      "إدخال الرقم الوطني الموحد وتحميل بيانات المنشأة",
      "التحقق من النشاط والملاك وإدخال العنوان",
      "الموافقة على الشروط و«سجّل المنشأة»",
    ],
    fees: "مجاناً (تأشيرة العمل الدائمة: 2,000 ريال لوزارة الداخلية)",
    duration: "فوري",
    sources: [
      "https://qiwa.sa/ar/business-owners/create-new-establishment/how-register-new-establishment-qiwa",
      "https://my.gov.sa/ar/services/24434",
      "https://qiwa.sa/ar/business-owners/hire-employees/how-issue-permanent-work-visas",
    ],
    keywords: ["قوى", "عمالة", "تأشيرة عمل", "توظيف", "استقدام"],
    lastVerified: VERIFIED,
  },
  {
    id: "mudad-wps",
    name: "رفع ملف حماية الأجور (مدد)",
    entityId: "mudad",
    category: "labor",
    description:
      "رفع ملف الأجور الشهري عبر بوابة الالتزام في منصة مدد خلال 30 يوماً من تاريخ الاستحقاق (أول كل شهر ميلادي). عدم الالتزام يوقف خدمات مثل إصدار التأشيرات ونقل العمالة.",
    url: "https://mudad.com.sa/landing-page/compliance",
    requirements: [
      { id: "md-unified", label: "الرقم الموحد للمنشأة لدى وزارة الموارد البشرية", kind: "document" },
      { id: "md-gosi", label: "الموظفون مسجلون في التأمينات الاجتماعية", kind: "document" },
      { id: "md-bank", label: "حساب بنكي لكل عامل", kind: "condition", description: "لا يُقبل الدفع النقدي." },
    ],
    prerequisites: ["gosi-register"],
    steps: [
      "تسجيل الدخول على منصة مدد واختيار المنشأة",
      "رفع الملفات → رفع ملف جديد",
      "اختيار شهر الأجور ونوع الأجر",
      "اختيار الملف والموافقة على الإقرار → رفع",
      "متابعة نسبة الالتزام وتبرير المخالفات",
    ],
    fees: "مجاناً",
    duration: "فوري (معالجة لحظية)",
    sources: ["https://my.gov.sa/ar/services/19988", "https://mudad.com.sa/landing-page/compliance", "https://mudad.com.sa/landing-page/faq?tab=WPS"],
    keywords: ["مدد", "حماية الأجور", "رواتب", "أجور"],
    lastVerified: VERIFIED,
  },
  {
    id: "freelance-license",
    name: "إصدار وثيقة العمل الحر",
    entityId: "freelance",
    category: "business",
    description:
      "وثيقة رسمية لممارسة العمل الحر في مهنة معتمدة بدون سجل تجاري، صالحة لسنة. لا تخوّل فتح محل أو استقدام عمالة (هذه مرتبطة بالسجل التجاري).",
    url: "https://freelance.sa",
    requirements: [
      { id: "fl-id", label: "سعودي الجنسية وعمر 18 سنة فأكثر", kind: "condition" },
      { id: "fl-absher", label: "حساب أبشر مفعّل (النفاذ الوطني)", kind: "condition" },
      { id: "fl-docs", label: "مرفقان على الأقل يثبتان المهنة", kind: "document", description: "مؤهل علمي، أو شهادات تدريبية، أو حساب يعرض نماذج أعمال، أو عقد تقديم خدمات." },
      { id: "fl-prelicense", label: "ترخيص مسبق لبعض الفئات (عقار، محاسبة، إرشاد سياحي، عربات أطعمة...)", kind: "document" },
    ],
    prerequisites: [],
    steps: ["الدخول إلى منصة العمل الحر والتحقق عبر نفاذ", "إنشاء حساب", "اختيار الفئة والنشاط والمهنة", "إرفاق متطلبات الإصدار", "استلام حالة الطلب عبر SMS"],
    fees: "مجاناً",
    duration: "فوري إلى 3 أيام عمل بعد مراجعة المرفقات",
    sources: ["https://my.gov.sa/ar/services/18485", "https://freelance.sa/faqs", "https://www.hrsd.gov.sa/ar/ministry-services/services/تجديد-وثيقة-العمل-الحر"],
    keywords: ["عمل حر", "فريلانس", "وثيقة", "مستقل"],
    lastVerified: VERIFIED,
  },
  {
    id: "trademark",
    name: "تسجيل علامة تجارية",
    entityId: "saip",
    category: "business",
    description: "حماية اسم أو شعار المشروع بتسجيله كعلامة تجارية لمدة 10 سنوات قابلة للتجديد.",
    url: "https://www.saip.gov.sa/ar/services/trademarks/تسجيل-علامة-تجارية",
    requirements: [
      { id: "tm-logo", label: "صورة العلامة / الشعار", kind: "document" },
      { id: "tm-class", label: "تحديد فئة المنتجات أو الخدمات", kind: "condition" },
      { id: "tm-auth", label: "للمنشآت: تفويض من المسؤول المخوّل (ووكالة موثقة للوكيل)", kind: "document" },
      { id: "tm-fees", label: "سداد الرسوم: 1,000 دراسة + 500 نشر + 5,000 تسجيل", kind: "condition" },
    ],
    prerequisites: [],
    steps: [
      "الدخول إلى بوابة العلامات التجارية عبر النفاذ الوطني",
      "طلب تسجيل علامة جديدة وتعبئة البيانات",
      "سداد فاتورة الدراسة (1,000 ريال) → الدراسة خلال 90 يوم عمل",
      "عند القبول: سداد فاتورة النشر (500 ريال) → النشر 60 يوماً",
      "بعد النشر دون اعتراض: سداد الفاتورة النهائية (5,000 ريال) خلال 30 يوماً وطباعة الشهادة",
    ],
    fees: "6,500 ريال إجمالاً",
    duration: "نحو 90 يوم عمل + 60 يوم نشر",
    sources: ["https://www.saip.gov.sa/ar/services/trademarks/تسجيل-علامة-تجارية", "https://my.gov.sa/ar/services/245210"],
    keywords: ["علامة تجارية", "شعار", "براند", "ملكية فكرية"],
    lastVerified: VERIFIED,
  },
];
